Ghazy\BlogBundle\Entity\Comment:
  type: entity
  table: comment
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    body:
      type: text
    is_activated:
      type: boolean
      nullable: false
    email:
      type: string
      length: 255
    created_at:
      type: datetime
    updated_at:
      type: datetime
      nullable: true
  manyToOne:
    post:
      targetEntity: Post
      inversedBy: comments
      joinColumn:
        name: post_id
        referencedColumnName: id
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]
    preUpdate: [ setUpdatedAtValue ]