Ghazy\BlogBundle\Entity\Post:
  type: entity
  table: post
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 255
      nullable: true
    body:
      type: text
    token:
      type: string
      length: 255
      unique: true
    is_activated:
      type: boolean
      nullable: false
    created_at:
      type: datetime
    updated_at:
      type: datetime
      nullable: true
  oneToMany:
    comments:
      targetEntity: Comment
      mappedBy: post
  manyToMany:
    tags:
      targetEntity: Tag
      inversedBy: posts
      joinTable:
        name: tag_post
        joinColumns:
          tag_id:
            referencedColumnName: id
        inverseJoinColumns:
          post_id:
            referencedColumnName: id
  lifecycleCallbacks:
    prePersist: [ setTokenValue, setCreatedAtValue ]
    preUpdate: [ setUpdatedAtValue ]
